# Generated by Django 2.0.5 on 2018-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_remove_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
