# Generated by Django 2.0.5 on 2018-11-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prject_id', models.IntegerField()),
                ('programer_id', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
