# Generated by Django 2.0.5 on 2018-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_auto_20181107_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
